### PR TITLE
add a algorithm of codeforces question

### PR DESCRIPTION
**Pull request by ShashwatSamadhiya**
codeforce round #746 div 2

### CODE REVIEW

**Comment by onosyoono** [comment]
Please provide a description for the challenges

**Comment by ShashwatSamadhiya** [comment]
code forces round #746 div 2

**Comment by ShashwatSamadhiya** [comment]
question id 1592A

**Comment by ShashwatSamadhiya** [comment]
i have added a description

**Comment by onosyoono** [comment]
Thank you

**Pull request merged**
